#!/bin/bash
# ==============================================================================
# Xiaozhi ESP32 Server - HAOS Add-on Entrypoint
# Reads add-on options from /data/options.json, generates server config, starts app
# ==============================================================================
set -e

SERVER_DIR="/opt/xiaozhi-esp32-server"
CONFIG_FILE="${SERVER_DIR}/data/.config.yaml"
OPTIONS_FILE="/data/options.json"

echo "[INFO] Reading add-on configuration..."

# Read options from HAOS options.json using jq
ANTHROPIC_API_KEY=$(jq -r '.anthropic_api_key // ""' "${OPTIONS_FILE}")
MODEL_NAME=$(jq -r '.model_name // "claude-sonnet-4-6"' "${OPTIONS_FILE}")
LANGUAGE=$(jq -r '.language // "fr"' "${OPTIONS_FILE}")
TTS_VOICE=$(jq -r '.tts_voice // ""' "${OPTIONS_FILE}")
PROMPT=$(jq -r '.prompt // "Tu es un assistant IA intelligent. Sois concis."' "${OPTIONS_FILE}")

# Get HA Supervisor token (injected by HAOS Supervisor as env var)
HA_TOKEN="${SUPERVISOR_TOKEN:-}"

# Determine TTS voice based on language if not explicitly set
if [ -z "${TTS_VOICE}" ]; then
    case "${LANGUAGE}" in
        fr) TTS_VOICE="fr-FR-HenriNeural" ;;
        en) TTS_VOICE="en-US-GuyNeural" ;;
        zh) TTS_VOICE="zh-CN-XiaoxiaoNeural" ;;
        *)  TTS_VOICE="fr-FR-HenriNeural" ;;
    esac
fi

# Build HA devices YAML list from options (safe jq array iteration)
HA_DEVICES=""
DEVICE_COUNT=$(jq '.ha_devices | length' "${OPTIONS_FILE}")
if [ "${DEVICE_COUNT}" -gt 0 ] 2>/dev/null; then
    for i in $(seq 0 $((DEVICE_COUNT - 1))); do
        device=$(jq -r ".ha_devices[$i]" "${OPTIONS_FILE}")
        HA_DEVICES="${HA_DEVICES}
      - \"${device}\""
    done
fi

# Default device entry if none configured
if [ -z "${HA_DEVICES}" ]; then
    HA_DEVICES="
      - \"salon,example_device,light.example\""
fi

# Get local IP for WebSocket/OTA URLs
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
if [ -z "${LOCAL_IP}" ]; then
    LOCAL_IP="0.0.0.0"
fi

# Indent multi-line prompt (ensure each line has 2-space YAML indentation)
PROMPT_INDENTED=$(echo "${PROMPT}" | sed 's/^/  /')

echo "[INFO] Configuration:"
echo "[INFO]   LLM Model: ${MODEL_NAME}"
echo "[INFO]   Language: ${LANGUAGE}"
echo "[INFO]   TTS Voice: ${TTS_VOICE}"
echo "[INFO]   Local IP: ${LOCAL_IP}"
echo "[INFO]   HA Token: ${HA_TOKEN:+set}${HA_TOKEN:-not set}"
echo "[INFO]   HA Devices: ${DEVICE_COUNT:-0}"

# Ensure data directory exists
mkdir -p "${SERVER_DIR}/data"

# Generate data/.config.yaml
cat > "${CONFIG_FILE}" << ENDOFCONFIG
# Auto-generated by Xiaozhi HAOS add-on - do not edit manually
server:
  ip: 0.0.0.0
  port: 8000
  http_port: 8003
  websocket: "ws://${LOCAL_IP}:8000/xiaozhi/v1/"
  vision_explain: "http://${LOCAL_IP}:8003/mcp/vision/explain"
  timezone_offset: +1
  auth:
    enabled: false

selected_module:
  VAD: SileroVAD
  ASR: SherpaASR
  LLM: ClaudeLLM
  TTS: EdgeTTS
  Memory: nomem
  Intent: function_call

LLM:
  ClaudeLLM:
    type: Claude
    model_name: "${MODEL_NAME}"
    api_key: "${ANTHROPIC_API_KEY}"
    max_tokens: 4096
    temperature: 0.7

TTS:
  EdgeTTS:
    type: edge
    voice: "${TTS_VOICE}"
    output_dir: tmp/

ASR:
  SherpaASR:
    type: sherpa_onnx_local
    model_dir: models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17
    output_dir: tmp/
    model_type: sense_voice

VAD:
  SileroVAD:
    type: silero
    threshold: 0.5
    threshold_low: 0.3
    model_dir: models/snakers4_silero-vad
    min_silence_duration_ms: 200

Intent:
  function_call:
    type: function_call
    functions:
      - change_role
      - get_weather
      - get_news_from_newsnow
      - hass_get_state
      - hass_set_state
      - hass_play_music

plugins:
  home_assistant:
    devices:${HA_DEVICES}
    base_url: "http://supervisor/core"
    api_key: "${HA_TOKEN}"

prompt: |
${PROMPT_INDENTED}
ENDOFCONFIG

echo "[INFO] Configuration generated at ${CONFIG_FILE}"
echo "[INFO] Starting Xiaozhi ESP32 Server..."

cd "${SERVER_DIR}"
exec python3 app.py
